#!/bin/bash

# Quick reference for deployment commands

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Job Pipeline Deployment Quick Reference           ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 LOCAL DEVELOPMENT"
echo "─────────────────────────────────────────────────────────────"
echo "  Run both backend and frontend:"
echo "    ./start-dev.sh"
echo ""
echo "  Or manually:"
echo "    Backend:  cd backend && npm run dev"
echo "    Frontend: cd frontend && npm run dev"
echo ""
echo ""
echo "🚀 RAILWAY DEPLOYMENT"
echo "─────────────────────────────────────────────────────────────"
echo "  1. See RAILWAY_DEPLOYMENT.md for step-by-step guide"
echo "  2. Backend URL will be like: https://job-pipeline-backend.railway.app"
echo "  3. Frontend URL will be like: https://job-pipeline-frontend.vercel.app"
echo ""
echo ""
echo "🎨 RENDER DEPLOYMENT"
echo "─────────────────────────────────────────────────────────────"
echo "  1. See RENDER_DEPLOYMENT.md for step-by-step guide"
echo "  2. Backend URL will be like: https://job-pipeline-backend.onrender.com"
echo "  3. Frontend URL will be like: https://job-pipeline-frontend.onrender.com"
echo ""
echo ""
echo "📝 ENVIRONMENT FILES"
echo "─────────────────────────────────────────────────────────────"
echo "  Backend Config:  backend/.env (copy from backend/.env.example)"
echo "  Frontend Config: frontend/.env.local"
echo ""
echo ""
echo "🔗 KEY URLS"
echo "─────────────────────────────────────────────────────────────"
echo "  Local Backend Health:  http://localhost:4000/health"
echo "  Local Backend API:     http://localhost:4000/api/jobs"
echo "  Local Frontend:        http://localhost:5173"
echo ""
echo ""
echo "⚙️  ARCHITECTURE"
echo "─────────────────────────────────────────────────────────────"
echo "  Backend:  Node.js Express (port 4000)"
echo "  Frontend: React + Vite (port 5173)"
echo "  Database: Supabase"
echo "  Storage:  Google Sheets + Supabase"
echo ""
echo "  Frontend requests data from Backend via HTTP API"
echo "  Backend connects to Supabase for data"
echo ""
echo ""
echo "📚 DOCUMENTATION"
echo "─────────────────────────────────────────────────────────────"
echo "  General Deployment:   DEPLOYMENT.md"
echo "  Railway Guide:        RAILWAY_DEPLOYMENT.md"
echo "  Render Guide:         RENDER_DEPLOYMENT.md"
echo ""
